// data/data.json is generated by `pnpm prebuild` and gitignored. This gives it a
// type when it hasn't been generated yet, so typechecking doesn't need the network.
declare module "*/data/data.json" {
  import type { Data } from "@/types/types";
  const data: Data;
  export default data;
}
